name: Update-Progress

on:
  push:
    branches-ignore:
      - "ch**"

  workflow_dispatch:
    inputs:
      purpose:
        description: "Purpose to manually run"
        required: true
        default: "test"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      FILE_NAME: "progress.png"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo your purpose
        if: ${{ github.event.inputs.purpose != '' }}
        run: |
          echo "Purpose: ${{ github.event.inputs.purpose }}"

      - name: Print Python info
        run: |
          echo "python  --version: `python --version`"
          echo "python3 --version: `python3 --version`"

      - name: Update ${{ env.FILE_NAME }}
        run: |
          python -m pip install -r .automation/requirements.txt
          python .automation/make_progress.py

      - name: Configure your Git username/email
        run: |
          git config user.name ${NAME}
          git config user.email ${EMAIL}
        env:
          NAME: "taishi-n"
          EMAIL: "taishi.m.and.p@gmail.com"

      - name: Commit ${{ env.FILE_NAME }}
        run: |
          git add $FILE_NAME
          git diff-index --quiet HEAD || git commit -m "bot: Update progress"
          git push
